run_id: "20250107_aviti"

duckdbrc_slurm: "/raven/u/thosi/dev/projects/wide-variant/config/duckdbrc-slurm"

directories:
  data: "/raven/ptmp/thosi/baby-biome/data"
  resources: "/raven/ptmp/thosi/baby-biome/resources"
  logs: "/raven/ptmp/thosi/baby-biome/logs"
  work: "/raven/ptmp/thosi/baby-biome/work"

wildcards:
  family: "B002"
  library: "230913_B002_B001_Lib|240704_B002_B001_Lib_AVITI_reseq"
  resource: "fastqs|samples|sequencing"
  species_plate: "Escherichia_coli"
  species_ref: "Escherichia_coli"

cohorts:
  aviti:
    family: "B002"
    library: "240704_B002_B001_Lib_AVITI_reseq"
    species: "Escherichia_coli"

  illumina:
    family: "B002"
    library: "230913_B002_B001_Lib"
    species: "Escherichia_coli"

tools:
  # Options: "bactmap|sarek_bcftools|sarek_freebayes|sarek_haplotypecaller|snippy"
  mapping: "bactmap|sarek_bcftools|sarek_freebayes|sarek_haplotypecaller"

params:
  bactmap:
    config: "/nexus/posix0/MPIIB-keylab/config/nextflow/bactmap.config"
    # Using extra: "--subsampling_off" turns off sub-sampling
    extra: ""
    pipeline: "/nexus/posix0/MPIIB-keylab/tools/nf-core/bactmap/1_0_0/"
    profiles:  "singularity" # Old pipeline, must use singularity instead of apptainer
    version: "1.0.0"

  legacy_mapping:
    cutadapt_pe:
      adapters: "-a CTGTCTCTTAT -a AGATCGGAAGAGC -A CTGTCTCTTAT -A AGATCGGAAGAGC"
      extra: "--minimum-length 1 -q 20"
    sickle_pe:
      qual_type: "sanger"
      extra: "-g -q 20 -l 50 -x -n"
    num_reads: 250000
    bowtie2_align:
      extra: "-X 2000 --no-mixed --dovetail"
    picard_markduplicates:
      extra: "--REMOVE_DUPLICATES true --ASO coordinate --VALIDATION_STRINGENCY SILENT"
    samtools_mpileup:
      extra: "-q30 -x -s -O -d3000"
    bcftools_mpileup:
      extra: "--max-depth 3000 --min-MQ 30"
    bcftools_call:
      caller: "--multiallelic-caller"
    bcftools_view:
      extra: "-Oz -v snps -q .75"
    tabix_index: "-p vcf"

  reference_genome:
    minimum_fraction_reference: ".5"
    minimum_readspow_reference: 3

  sarek:
    config: "/nexus/posix0/MPIIB-keylab/config/nextflow/sarek.config"
    extra: "--trim_fastq --length_required 50 --skip_tools baserecalibrator"
    pipeline: "/nexus/posix0/MPIIB-keylab/tools/nf-core/sarek/3_5_0/"
    profiles: "apptainer"
    tools: "freebayes,haplotypecaller,mpileup"
    version: "3.5.0"

  snippy:
    basequal: 20
    # Options: "--quiet --cleanup --report"
    extra: "--quiet"
    mapqual: 30
    mincov: 1
    minfrac: ".05"
    minqual: 25

  srst2:
    extra: "--forward '_1.trim' --reverse '_2.trim' --mlst_delimiter '_'"

  taxprofiler:
    config: "/nexus/posix0/MPIIB-keylab/config/nextflow/taxprofiler.config"
    databases: "/nexus/posix0/MPIIB-keylab/config/nextflow/taxprofiler_databases.csv"
    extra: "--perform_shortread_qc --shortread_qc_minlength 50 --run_kraken2 --run_bracken --run_profile_standardisation --taxpasta_ignore_errors"
    pipeline: "/nexus/posix0/MPIIB-keylab/tools/nf-core/taxprofiler/1_2_1/"
    profiles:  "apptainer"
    version: "1.2.1"
  
  variant_filter:
    ad_ge: 10
    ad_strand_ge: 2
    alt_density_window_half_size: 10
    dp_ge: 10
    epp_lt: 20
    maf_ge: ".95"
    mq_ge: 20
    quality_ge: 25
    sp_lt: 20
